apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: "2222"
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job3
        - job2
        - job1
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job2:
      needs: job1
      steps:
        - run: echo "hello world"
          uses: docker://golang:1.20.3-alpine3.17
          name: Hello world
          shell: sh
  job3:
      needs: job2
      steps:
        - run: echo "hello world"
          uses: docker://golang:1.20.3-alpine3.17
          name: Hello world
          shell: sh
