apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: a-approval-standard
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approve
  approve:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 0908d292-df35-11eb-ba33-42010a83ae11
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        {}
