apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aa-secrets
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
        - aaa
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
  aaa:
    needs:
      - deploy-to-Prod
    uses: https://example.cloudbees/path/to/file.yaml
    with:
      aa: ww
    secrets:
      aa: aa
