apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aaa-aaa
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - build
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
