apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aaaaa-staged
on:
  workflow_dispatch:
    inputs:
      www:
        type: string
        required: true
        description: www
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
