apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: approval-old
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
        - approval
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
  approval:
    needs:
      - deploy-to-Prod
    timeout-minutes: 4320
    with:
      instructions: qqq
      disallowLaunchByUser: true
      approvers: 3e95cfd2-4c93-11ee-b6d6-42010a83ae76,4bc37dfe-459a-11ed-a6a3-42010a83ae66,c7787670-03d4-11eb-9d67-42010a83ae35,de39a936-7a04-11ec-81d0-42010a83ae75,0908d292-df35-11eb-ba33-42010a83ae11,bcb10a62-d9ec-11ee-aea9-42010a83ae92
      notifyAllEligibleUsers: false
      approvalInputs: |
        www:
          type: string
          default: www
          required: true
          description: www
        ttt:
          type: choice
          options:
            - ttt
            - yyy
            - uuu
          default: ""
          required: true
          description: ttt
        eee:
          type: number
          default: 333
          required: true
          description: eee
        rrr:
          type: boolean
          default: true
          required: true
          description: rrr
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
