apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: approval-3
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - build
jobs:
  build:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
