apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: null
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0,15,30,45 * * * *
  workflow_call: null

jobs:
  Prodsupersupersupersuperlongsssssssssssssssssssa:
    steps:
      - run: echo "Deploying to Prod"
        uses: docker://golang:1.20.3-alpine3.17
        name: Prodsupersupersupersuperlongsssssssssssssssssssa
        shell: sh
