apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage
      jobs:
        - job
        - b
        - c
    - name: Stage1
      jobs:
        - job1
jobs:
  job:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job1:
    needs: c
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  b:
    needs: job
    steps:
      - uses: b
        name: b
  c:
    steps:
      - uses: c
        name: c
      - uses: a
        name: a
      - uses: aaa
        name: aaa
