apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: pre-prod
      jobs:
        - entrygate
jobs:
  entrygate:
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  deploy:
    steps:
      - run: echo "Deploying to Prepod"
        uses: docker://golang:1.20.3-alpine3.17
        name: deploy
        shell: sh
  exitgate:
    timeout-minutes: 4320
    with:
      instructions: ""
      disallowLaunchByUser: false
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      notifyAllEligibleUsers: false
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
