apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
        - job2
        - job4
        - job3
    - name: Stage
      jobs:
        - job
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
    needs: job4
  job2:
    steps:
      - uses: a
        name: a
    needs: job3
  job3:
    steps:
      - uses: b
        name: b
    needs: job1
  job4:
    steps:
      - uses: c
        name: c
    needs: job2
