apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
        - dfcfvrfv
        - qwwqdd
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  dfcfvrfv:
    needs: job1
    steps:
      - uses: rvrv
  qwwqdd:
    needs:
      - dfcfvrfv
    steps:
      - uses: test
