apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  Prodsupersupersupersuperlong@@@@sa:
    steps:
      - run: echo "Deploying to Prod"
        uses: docker://golang:1.20.3-alpine3.17
        name: Prodsupersupersupersuperlongsssssssssssssssssssa
        shell: sh
