apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - deploy-to-Prod
        - b
        - c
jobs:
  deploy-to-Prod:
    steps:
      - name: Deploy to Prod
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Deploying to Prod"
    needs: []
  b:
    needs:
      - deploy-to-Prod
    steps:
      - uses: b
        name: b
  c:
    needs:
      - b
    steps:
      - uses: c
        name: c
