apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: StageC
      jobs:
        - c1
        - c2
        - c3
    - name: StageA
      jobs:
        - a1
        - a2
        - a3
    - name: Stage
      jobs:
        - b1
        - b2
        - b3
jobs:
  c1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
  c2:
    needs: c1
    steps:
      - uses: c
        name: c
  c3:
    needs: c2
    steps:
      - uses: c
        name: c
  a1:
    needs: c3
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  a2:
    needs: a1
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  a3:
    needs: a2
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  b1:
    needs: a3
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  b2:
    needs: b1
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  b3:
    needs:
      - b2
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
