apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Stage1
      jobs:
        - job2
        - c
    - name: Stage caca
      jobs:
        - job1
        - a
    - name: Stage
      jobs:
        - job
        - b
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
    needs: c
  job:
    needs: a
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job2:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  a:
    needs: job1
    steps:
      - uses: a
        name: a
  b:
    needs: job
    steps:
      - uses: b
        name: b
  c:
    needs:
      - job2
    steps:
      - uses: c
        name: c
