apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  schedule:
    - cron: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 * * 6 *
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
