apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: A sample manifest should go here, to help user
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - a
jobs:
  a:
    steps:
      - run: echo "Deploying to Prod"
        uses: docker://golang:1.20.3-alpine3.17
        name: Daeploy to Prod
        shell: sh
