apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch: null
metadata:
  stages/v1alpha1:
    - name: Prod
      jobs:
        - a
        - b
        - c
jobs:
  a:
    needs:
      - c
    steps:
      - uses: a
        name: a
  b:
    needs:
      - c
    steps:
      - uses: b
        name: b
  c:
    needs:
      - a
    steps:
      - uses: c
        name: c
